### PR TITLE
To make it easier for the preprocessor

### PR DESCRIPTION
**Pull request by firefish111**
Added the new `extern` command from v3.3. @DynamicSquid 
Also is `add_back` or `push_back` better? `push_back` is like more common

### CODE REVIEW

**Comment by DynamicSquid** [comment]
wait what does the use and extern thingy do again?

**Comment by firefish111** [comment]
@DynamicSquid `use` imports a dusk package, `extern` imports a local package.
`use x` is equivalent to `extern dusk_pkgs/x`

**Comment by DynamicSquid** [comment]
Hmm... but i want it so that the user doesnt need to tpuse the command line to install packages. Is there a way i can install packages using c++? Or do I have to do some c++ piping work

**Comment by firefish111** [comment]
@DynamicSquid Well why? that's how node and python do it, if you are used to repl.it's automatic stuff, then don't be

**Comment by DynamicSquid** [comment]
Yeah true I guess. But don't you think it'd get a little complicated? I feel like we should have built in C++ code that executes the shell command automatically

**Comment by firefish111** [comment]
@DynamicSquid Or we could combine the two into one massive binary an order of magnitude bigger (not that big, I'm exaggerating)

**Comment by DynamicSquid** [comment]
So we have the package manager binary, and then language binary?

**Comment by firefish111** [comment]
# @DynamicSquid Am I a time traveller or something?
image

**Comment by DynamicSquid** [comment]
wait wtf

**Comment by firefish111** [comment]
@DynamicSquid All inside one thing yeah. Remember that chat we had about combining object files? r making dusk an `.so` file (linux equivalent of a `.dll` file) so that it'd be easier to use?
But the trade-off was `night run path/to/file/night` and `night add pkg` `night del pkg` `night search k` `night info pkg` `night list pkg` and so on

**Comment by DynamicSquid** [comment]
wait i've been doing c++ for 14 months and I still don't know what an object file is lol

**Comment by firefish111** [comment]
@DynamicSquid It's not C++ specific:
The compilation process that `g++` performs is split into two main processes: compiling and linking.
# Preprocessing:
Replaces the `#include myheader.h` in `main.c` with the contents of `myheader.h`.
So from
```cpp
#include "myheader.h"

int main(void) {
    return squid(111, 32);
}
```
to
```cpp
# 1 myheader.h
int squid(int a, int b) {
   return a - b;
}

# 2 main.c
int main(void) {
    return squid(111, 32);
}
```
# Compiling:
Takes the contents of the now pre-processed `main.c` and converts it to `/tmp/7d4fdg534.o` (it's random every time)
The object file is a binary file, that contains everything in your code, except it's not executable, in other words you can't run it.
# Linking:
The command `ld` is used for this.
`g++` calls `ld` without you even knowing.
All `ld` does is makes your object file and puts it in an executable binary, `a.out`.

**Comment by DynamicSquid** [comment]
gotcha!

**Comment by firefish111** [comment]
@DynamicSquid Great, you understand. The thing is A thing called CGo allows you to compile go applications into these magical object files, or into an `.so` file (the windows equivalent of a `.dll` file)

**Comment by DynamicSquid** [comment]
what's  .dll file?

**Comment by firefish111** [comment]
@DynamicSquid a Dynamic Linked library.
basically a file that contains code that cans be used by more than one program at the same time, while making it more efficient so that there is only one copy of the code loaded into memory at any given time.

**Comment by DynamicSquid** [comment]
Oh, so a static linked library is the same but there is multiple copies of the code in memory?

**Comment by firefish111** [comment]
@DynamicSquid yup

**Comment by DynamicSquid** [comment]
Wait sorry what's this PR for?

**Comment by firefish111** [comment]
@DynamicSquid To add compatibility with the new extern

**Comment by DynamicSquid** [comment]
What does the extern do? Can't we manage the files in Night, not here?

**Comment by firefish111** [comment]
@DynamicSquid `extern` is local files, `use` is dusk files. `use x` is equivalent to `extern dusk_pkgs/x`.

**Pull request closed without merging**
